title: Feliz La Vida
description: lion blog

url: http://lionkang.github.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: Thinking
   url: /thinking
 - title: Enjoy
   url: /enjoy
 - title: About
   url: /about
 
social:
   github: lionkang
   twitter: lionkang
   facebook: mario.kang.75
   email: lionkang@gmail.com

google_analytics: ""
