title: Feliz La Vida
description: Enjoy Life <br> Pleasure Together <br> Dreaming of an Altruistic Life 

url: http://lionkang.github.io
baseurl: ""
#paginate_path: "blog/page:num/"
#permalink: blog/:title/
permalink: pretty

#markdown: kramdown
#highlighter: rouge
#gems: [jekyll-paginate]
#paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: Categorys
   url: /categorys
 - title: Tags
   url: /tags
 - title: Links
   url: /links
 - title: About
   url: /about
 
social:
   github: lionkang
   twitter: lionkang
   facebook: mario.kang.75
   email: lionkang@gmail.com

google_analytics: "UA-116176149-1"


#title:               Lanyon
#tagline:             'A Jekyll theme'
#description:         'A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
#url:                 http://lanyon.getpoole.com
#baseurl:             ''
gems: [jekyll-paginate]
paginate:           3

# About/contact
author:
  name:              LionKang
  url:               https://twitter.com/lionkang
  email:             lionkang@gmail.com

# Custom vars
version:             1.0.1
