# Site settings
title: Feliz La Vida
description: Enjoy Life <br> Pleasure Together <br> Dreaming of an Altruistic Life 
baseurl: ""
url: https://lionkang.github.io

# Author
author:
  name: LionKang
  url: https://www.facebook.com/mario.kang.75
  email: lionkang@gmail.com

# Build settings
markdown: kramdown

# Assets
sass:
  sass_dir: _sass
  style: compressed

# Gems
gems: [jekyll-paginate]

# Permalinks
permalink: /:year-:month-:day/:title
paginate: 5

# Google analytics
google_analytics: "UA-116176149-1"